export const assetsObject = {
  // Category Images
  C1: require('../../../assets/CategoryIcons/C1.jpg'),
  C2: require('../../../assets/CategoryIcons/C2.jpeg'),
  C3: require('../../../assets/CategoryIcons/C3.jpg'),
  C4: require('../../../assets/CategoryIcons/C4.jpg'),
  C5: require('../../../assets/CategoryIcons/C5.jpg'),
  C6: require('../../../assets/CategoryIcons/C6.jpeg'),
  C7: require('../../../assets/CategoryIcons/C7.jpg'),
  C8: require('../../../assets/CategoryIcons/C8.jpg'),
  C9: require('../../../assets/CategoryIcons/C9.jpg'),
  C10: require('../../../assets/CategoryIcons/C10.jpg'),
  C11: require('../../../assets/CategoryIcons/C11.jpg'),
  C12: require('../../../assets/CategoryIcons/C12.jpeg'),
  C13: require('../../../assets/CategoryIcons/C13.jpg'),
  C14: require('../../../assets/CategoryIcons/C14.jpeg'),
  C15: require('../../../assets/CategoryIcons/C15.jpg'),
  C16: require('../../../assets/CategoryIcons/C16.jpg'),
  C17: require('../../../assets/CategoryIcons/C17.jpeg'),
  C18: require('../../../assets/CategoryIcons/C18.jpg'),
  C19: require('../../../assets/CategoryIcons/C19.jpg'),
  C20: require('../../../assets/CategoryIcons/C20.jpg'),
  C21: require('../../../assets/CategoryIcons/C21.jpg'),
  C22: require('../../../assets/CategoryIcons/C22.jpg'),
  C23: require('../../../assets/CategoryIcons/C23.jpg'),
  C24: require('../../../assets/CategoryIcons/C24.jpg'),
  C25: require('../../../assets/CategoryIcons/C25.jpg'),
  C26: require('../../../assets/CategoryIcons/C26.jpg'),
  C27: require('../../../assets/CategoryIcons/C27.jpg'),
  C28: require('../../../assets/CategoryIcons/C28.jpg'),
  C29: require('../../../assets/CategoryIcons/C29.jpg'),
  C30: require('../../../assets/CategoryIcons/C30.jpg'),
  C31: require('../../../assets/CategoryIcons/C31.jpg'),
  C32: require('../../../assets/CategoryIcons/C32.jpg'),
  C33: require('../../../assets/CategoryIcons/C33.jpg'),
  C34: require('../../../assets/CategoryIcons/C34.jpg'),
  C35: require('../../../assets/CategoryIcons/C35.jpg'),
  C36: require('../../../assets/CategoryIcons/C36.jpg'),
  C37: require('../../../assets/CategoryIcons/C37.jpg'),
  C38: require('../../../assets/CategoryIcons/C38.jpg'),

  // Main Images
  1: require('../../../assets/logo.png'),
  2: require('../../../assets/3.jpg'),
  3: require('../../../assets/2.jpeg'),
  4: require('../../../assets/4.png'),
  5: require('../../../assets/4.png'),
  6: require('../../../assets/5.png'),
  7: require('../../../assets/2.jpeg'),
};
